from app.resume_loader import build_resume_facts

RESUME_FACTS = build_resume_facts()

SUGGESTED_QUESTIONS = {
    "en": [
        "What are Lu's strongest technical areas?",
        "What's the biggest performance win Lu has shipped to production?",
        "How did Lu build an LLM agent reliable enough for a real bank?",
        "How has Lu's work spanned both e-commerce and financial AI?",
    ],
    "zh": [
        "汪露最擅长哪些技术方向？",
        "汪露交付过最大的性能优化是什么？",
        "汪露是怎么让 LLM Agent 在银行生产环境可靠运行的？",
        "汪露的经验是怎么覆盖电商和金融两个领域的？",
    ],
}


JD_SIGNALS = [
    {
        "id": "agent-orchestration",
        "requirement_en": "Agent orchestration, tool calling, workflow design, and state management",
        "requirement_zh": "Agent 编排、工具调用、工作流设计与状态管理",
        "evidence_en": "Built Zalando Assistant Agent Runtime with Tool Calling, typed Streaming events, multi-turn state, and OpenAI Responses API migration.",
        "evidence_zh": "构建 Zalando Assistant Agent Runtime，覆盖 Tool Calling、类型化 Streaming 事件、多轮状态与 OpenAI Responses API 迁移。",
        "senior_signal_en": "Can design the runtime loop, not only prompt a model.",
        "senior_signal_zh": "不仅会写 Prompt，而是能设计 Agent Runtime 循环。",
        "proof_project_ids": ["agent-runtime", "product-comparison"],
    },
    {
        "id": "evaluation",
        "requirement_en": "Evaluation systems, regression suites, LLM-as-judge, and quality gates",
        "requirement_zh": "评估体系、回归测试集、LLM-as-Judge 与质量门控",
        "evidence_en": "Built 1,000+ Text2SQL eval cases, 800+ product-detail scenarios, RAGAS-inspired retrieval and judge tests for this site.",
        "evidence_zh": "构建 1,000+ Text2SQL 评估用例、800+ 商品场景，并为本站搭建 RAGAS 思路的检索与 Judge 测试。",
        "senior_signal_en": "Treats evals as production infrastructure and regression protection.",
        "senior_signal_zh": "将评估作为生产基础设施与回归保护。",
        "proof_project_ids": ["text2sql", "rag-chatbot", "agent-runtime"],
    },
    {
        "id": "grounding-rag",
        "requirement_en": "RAG, hybrid retrieval, embeddings, reranking, and grounded answers",
        "requirement_zh": "RAG、混合检索、Embedding、Rerank 与可信回答",
        "evidence_en": "Built LlamaIndex + FAISS RAG pipeline, dual-layer field/value reranking, and evidence-card retrieval in the resume agent.",
        "evidence_zh": "构建 LlamaIndex + FAISS RAG、字段+值双层 Rerank，以及本站 evidence-card 检索。",
        "senior_signal_en": "Understands retrieval as a reliability layer, not a demo add-on.",
        "senior_signal_zh": "把检索视为可靠性层，而不是 Demo 附件。",
        "proof_project_ids": ["rag-chatbot", "text2sql"],
    },
    {
        "id": "latency-observability",
        "requirement_en": "Latency, observability, streaming UX, fallbacks, and production reliability",
        "requirement_zh": "延迟、可观测性、Streaming 体验、降级与生产可靠性",
        "evidence_en": "Reduced TTFT by 25%, reduced cold-start by 60%, added request logging, SSE events, provider fallback, and deterministic evidence fallback.",
        "evidence_zh": "TTFT 降低 25%，冷启动降低 60%，并具备请求日志、SSE 事件、多 Provider 降级和确定性证据兜底。",
        "senior_signal_en": "Optimizes AI systems against user-perceived latency and failure modes.",
        "senior_signal_zh": "围绕用户感知延迟和失败模式优化 AI 系统。",
        "proof_project_ids": ["agent-runtime", "personalization"],
    },
    {
        "id": "product-fullstack",
        "requirement_en": "Full-stack AI product delivery and user-facing interaction design",
        "requirement_zh": "全栈 AI 产品交付与面向用户的交互设计",
        "evidence_en": "Owned backend runtime, API contracts, streaming frontend terminal, evidence rendering, and product decision flows.",
        "evidence_zh": "覆盖后端 Runtime、API 契约、前端流式终端、证据渲染与商品决策流程。",
        "senior_signal_en": "Can turn model capability into a shippable product surface.",
        "senior_signal_zh": "能把模型能力转化为可上线的产品体验。",
        "proof_project_ids": ["product-comparison", "personalization", "agent-runtime"],
    },
    {
        "id": "enterprise-data",
        "requirement_en": "Enterprise data integration, SQL, permissions, and domain constraints",
        "requirement_zh": "企业数据集成、SQL、权限与业务约束",
        "evidence_en": "Built bank Text2SQL agent, SQL validation/retry, access-control domain model, reporting pipeline, and zero-downtime migration.",
        "evidence_zh": "构建银行 Text2SQL Agent、SQL 校验重试、权限领域模型、报表流水线与零感知迁移。",
        "senior_signal_en": "Can operate AI features inside regulated and data-heavy enterprise systems.",
        "senior_signal_zh": "能在强约束、重数据的企业系统中落地 AI 能力。",
        "proof_project_ids": ["text2sql", "pricing-management"],
    },
]


SENIOR_CAPABILITIES = [
    {
        "id": "runtime-architecture",
        "title_en": "Agent runtime architecture",
        "title_zh": "Agent Runtime 架构",
        "narrative_en": "Designs the loop that coordinates tools, state, streaming, providers, and fallback behavior.",
        "narrative_zh": "设计协调工具、状态、Streaming、Provider 与降级行为的运行循环。",
        "evidence_en": "Zalando Assistant runtime: Tool Calling, typed SSE Streaming, multi-turn state, OpenAI Responses API migration, -25% TTFT.",
        "evidence_zh": "Zalando Assistant Runtime：Tool Calling、类型化 SSE、多轮状态、Responses API 迁移，TTFT -25%。",
        "proof_project_ids": ["agent-runtime"],
        "keywords": ["Agent Runtime", "Tool Calling", "Streaming", "State Machine"],
    },
    {
        "id": "evaluation-systems",
        "title_en": "Evaluation and regression systems",
        "title_zh": "评估与回归体系",
        "narrative_en": "Builds eval loops that make AI changes measurable and safe to ship.",
        "narrative_zh": "构建让 AI 改动可度量、可安全上线的评估闭环。",
        "evidence_en": "1,000+ Text2SQL cases, 800+ recommendation scenarios, retrieval MRR and LLM-as-judge tests in CI/manual gates.",
        "evidence_zh": "1,000+ Text2SQL 用例、800+ 推荐场景、检索 MRR 与 LLM-as-Judge 测试。",
        "proof_project_ids": ["text2sql", "rag-chatbot"],
        "keywords": ["Evaluation", "RAGAS", "LLM-as-Judge", "Regression"],
    },
    {
        "id": "latency-reliability",
        "title_en": "Latency and production reliability",
        "title_zh": "延迟与生产可靠性",
        "narrative_en": "Optimizes AI products for real user traffic, not only benchmark demos.",
        "narrative_zh": "面向真实用户流量优化 AI 产品，而不仅是 Demo Benchmark。",
        "evidence_en": "-25% TTFT, -60% cold-start, -70% profile calls, deterministic fallback when model providers fail.",
        "evidence_zh": "TTFT -25%、冷启动 -60%、画像调用 -70%，模型失败时有确定性兜底。",
        "proof_project_ids": ["agent-runtime", "personalization"],
        "keywords": ["TTFT", "P99", "Caching", "Fallback"],
    },
    {
        "id": "model-code-boundary",
        "title_en": "Model/code boundary design",
        "title_zh": "模型与代码边界设计",
        "narrative_en": "Keeps probabilistic reasoning and deterministic business logic in the right places.",
        "narrative_zh": "把概率式推理和确定性业务逻辑放在各自合适的位置。",
        "evidence_en": "Product Comparison Skill: model handles intent and summary; deterministic code owns product resolution, discount math, and rendering markers.",
        "evidence_zh": "Product Comparison：模型负责意图和总结，代码负责商品定位、折扣计算与渲染标记。",
        "proof_project_ids": ["product-comparison"],
        "keywords": ["Structured Output", "Deterministic Rendering", "Multi-turn"],
    },
    {
        "id": "enterprise-ai",
        "title_en": "Enterprise AI and data systems",
        "title_zh": "企业 AI 与数据系统",
        "narrative_en": "Connects agent workflows to SQL, permissions, reporting, and operational data constraints.",
        "narrative_zh": "将 Agent 工作流连接到 SQL、权限、报表和运营数据约束。",
        "evidence_en": "Bank Text2SQL, SQL validation/retry, DDD access control, Tablesaw reporting, zero-impact migration.",
        "evidence_zh": "银行 Text2SQL、SQL 校验重试、DDD 权限、Tablesaw 报表与零感知迁移。",
        "proof_project_ids": ["text2sql", "pricing-management"],
        "keywords": ["Text2SQL", "SQL Validation", "DDD", "Enterprise Data"],
    },
]
